Browse all category made responsive
MAVRICK-1/Nest-Ondc pull request #60
Opened 2024-06-04 16:10 UTC by captainsahil001

Made the browse all category button responsive and working 

## Description

Added all the subcategories of the button into a grid container and made it responsive and can be clicked to viewed using feature show more and show less

## Motivation and Context
It was one of the major bug and was needed to be fixed so made it alright now.

## Screenshots (if appropriate):
![Screenshot 2024-06-04 213629](https://github.com/MAVRICK-1/Nest-Ondc/assets/116186123/f0061a7c-80e4-4256-a552-21229929262a)
![Screenshot 2024-06-04 213645](https://github.com/MAVRICK-1/Nest-Ondc/assets/116186123/a5ba3576-61ff-4339-98ef-4c0708a168cc)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-06-04 16:14 UTC, captainsahil001 commented
pls check i have completed my task of issue #34 and merge to make my contribution in this project

2024-06-04 16:15 UTC, kushagra-singhh requested changes

2024-06-04 16:15 UTC, kushagra-singhh commented on src/assets/images/pet.svg
The dimensions of this image is not at par with others.

2024-06-04 16:22 UTC, captainsahil001 commented on src/assets/images/pet.svg
yes it was according to mavrick

2024-06-04 17:47 UTC, MAVRICK-1 commented on src/assets/images/pet.svg
@kushagra-singhh is right , @captainsahil001 can you update it

2024-06-04 18:33 UTC, captainsahil001 commented on src/assets/images/pet.svg
> @kushagra-singhh is right , @captainsahil001 can you update it

Can you suggest me the dimension which would be appropriate.

2024-06-05 05:56 UTC, kushagra-singhh commented on src/assets/images/pet.svg
pet.svg is smaller than the other images.

2024-06-05 06:01 UTC, captainsahil001 commented on src/assets/images/pet.svg
> pet.svg is smaller than the other images.

I think only this pet and milk one I need to set the dimension right

2024-06-05 06:18 UTC, kushagra-singhh commented on src/assets/images/pet.svg
Yes.

2024-06-05 07:16 UTC, kushagra-singhh approved these changes

2024-06-05 07:16 UTC, captainsahil001 reviewed
made the changes kindly check

2024-06-05 07:17 UTC, kushagra-singhh commented
> made the changes kindly check

Looks good !! 👍🏻

2024-06-05 08:47 UTC, MAVRICK-1 commented
@captainsahil001 great work @kushagra-singhh thanx 4 the help

2024-06-05 08:47 UTC, merged

2024-06-05 15:34 UTC, captainsahil001 reviewed
ok